#和风天气
qweather:
  #主配置
  config:
    keyName: ??
    publicId: ??
    key: ??
    type: ??
  # 城市配置
  city:
    config:
      city_name: 北京
      apiUrl: https://geoapi.qweather.com
  #天气配置
  weather:
    config:
      apiUrl: https://devapi.qweather.com
