alipay:
  config:
    # 沙箱环境地址，正式环境可不配置
    server-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
    seller-id: ??
    app-id: ??
    app-cert-path: ??
    aipay-public-cert-path: ??
    root-cert-path: ??
    private-key: ??
    alipay-public-key: ??
    notify-url: ??
